version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: echo npm install
      - run: CI=true npm run build
  text:
    docker: 
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "this is just a dummy test"
  hithere:
    docker: 
        - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Text?"
workflows:
  version: 2
  build_and_lint: # name of your workflow
    jobs:
      - build
      - hithere
      - text:
          requires:
            - hithere